kafka.bootstrap.servers=boot-xxx.kafka.us-east-1.amazonaws.com:9092
kafka.topic=game-action-logs
kafka.group.id=flink-kafka-iceberg-dynamic
kafka.startup.mode=latest-offset
iceberg.namespace=default
iceberg.table=game_action_logs
sink.target=s3tables
s3tables.warehouse=arn:aws:s3tables:us-east-1:123456789012:bucket/my-table-bucket
aws.region=us-east-1
sink.parallelism=2
checkpoint.interval=60000
